In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
crimerecord_2021="Resources/COBRA-2021.CSV"
crimerecord_202011="Resources/COBRA-2020.CSV"
crimerecord_2009_2019="Resources/COBRA-2009-2019.csv"
crimerecord_202009="Resources/COBRA-2020-old.CSV"

In [4]:
crimerecord_2021_df=pd.read_csv(crimerecord_2021,encoding="utf-8")
crimerecord_202009_df=pd.read_csv(crimerecord_202009,encoding="utf-8")
crimerecord_202011_df=pd.read_csv(crimerecord_202011,encoding="utf-8")
crimerecord_2009_2019_df=pd.read_csv(crimerecord_2009_2019,encoding="utf-8")

In [ ]:
crimerecord_2021_df.columns

In [ ]:
crimerecord_2021_df.head()

In [ ]:
crimerecord_202009_df.columns

In [ ]:
crimerecord_202009_df.head()

In [ ]:
crimerecord_202011_df.columns

In [ ]:
crimerecord_202011_df.head()

In [ ]:
crimerecord_2009_2019_df.columns

In [5]:
crimerecord_202009_clean=crimerecord_202009_df[['offense_id',  'occur_date', 'occur_time',  'location',
    'UC2_Literal','ibr_code', 'neighborhood', 'long', 'lat']]
crimerecord_202009_clean.head()

,offense_id,occur_date,occur_time,location,UC2_Literal,ibr_code,neighborhood,long,lat
0,200021209,1/2/2020,15:21,12 BROAD ST SW,HOMICIDE,NaN,Downtown,-84.39189,33.75352
1,200061707,1/6/2020,0:00,785 PEYTON AVE NW,HOMICIDE,NaN,Center Hill,-84.46770,33.77655
2,200100013,1/9/2020,23:45,1977 JONES AVE NW,HOMICIDE,NaN,West Highlands,-84.45208,33.78738
3,200151818,1/15/2020,17:15,549 JOSEPH LOWERY BLVD,HOMICIDE,NaN,West End,-84.41782,33.74001
4,200180440,1/18/2020,3:31,28 IRBY AVE NW,HOMICIDE,NaN,South Tuxedo Park,-84.38018,33.84102

In [6]:
crimerecord_2009_2019_clean=crimerecord_2009_2019_df[['Report Number', 'Occur Date', 'Occur Time', 'Location', 
       'UCR Literal','IBR Code','Neighborhood', 'Latitude','Longitude']]
crimerecord_2009_2019_clean.head()

,Report Number,Occur Date,Occur Time,Location,UCR Literal,IBR Code,Neighborhood,Latitude,Longitude
0,90010930,2009-01-01,1145,2841 GREENBRIAR PKWY,LARCENY-NON VEHICLE,2303,Greenbriar,33.68845,-84.49328
1,90011083,2009-01-01,1330,12 BROAD ST SW,LARCENY-NON VEHICLE,2303,Downtown,33.75320,-84.39201
2,90011208,2009-01-01,1500,3500 MARTIN L KING JR DR SW,LARCENY-NON VEHICLE,2303,Adamsville,33.75735,-84.50282
3,90011218,2009-01-01,1450,3393 PEACHTREE RD NE,LARCENY-NON VEHICLE,2303,Lenox,33.84676,-84.36212
4,90011289,2009-01-01,1600,2841 GREENBRIAR PKWY SW,LARCENY-NON VEHICLE,2303,Greenbriar,33.68677,-84.49773

In [7]:
crimerecord_202011_clean=crimerecord_202011_df[['offense_id',  'occur_date', 'occur_time', 'location', 
        'UC2_Literal','ibr_code','neighborhood', 'lat', 'long']]
crimerecord_202011_clean.head()

,offense_id,occur_date,occur_time,location,UC2_Literal,ibr_code,neighborhood,lat,long
0,203341346,11/29/2020,19:21,3050 M.L.K. JR DR SW,AGG ASSAULT,13A,Harland Terrace,33.751060,-84.486163
1,203631200,12/28/2020,17:21,1186 IRA ST SW,LARCENY-NON VEHICLE,23H,Pittsburgh,33.722696,-84.399763
2,203631285,12/24/2020,14:00,501 BOULEVARD PL NE,LARCENY-NON VEHICLE,23H,Old Fourth Ward,33.769680,-84.370736
3,203651634,12/30/2020,20:15,3101 PIEDMONT RD NE,LARCENY-FROM VEHICLE,23F,Peachtree Park,33.840653,-84.369361
4,203660108,12/31/2020,1:15,1974 SYLVAN RD SW,AGG ASSAULT,13A,Sylvan Hills,33.700432,-84.418128

In [8]:
crimerecord_2021_clean=crimerecord_2021_df[['offense_id', 'occur_date', 'occur_time', 'location', 'ibr_code', 'UC2_Literal',
       'neighborhood', 'lat', 'long']]

crimerecord_2021_clean.head()

,offense_id,occur_date,occur_time,location,ibr_code,UC2_Literal,neighborhood,lat,long
0,200006928,7/8/2020,10:00,1888 HOLLYWOOD RD NW,240,AUTO THEFT,Riverside,33.807140,-84.471539
1,200016928,6/13/2020,13:00,595 PIEDMONT AVE NE,23C,LARCENY-NON VEHICLE,Old Fourth Ward,33.770357,-84.381158
2,200201253,1/20/2021,04:00,2479 ABNER TERRACE NW,23G,LARCENY-FROM VEHICLE,Scotts Crossing,33.800999,-84.466556
3,201791305,10/5/2020,16:00,2143 PEACHTREE RD,23H,LARCENY-NON VEHICLE,NaN,33.812773,-84.391538
4,202101654,11/5/2020,19:37,177 MOURY AVE SE,13A,AGG ASSAULT,The Villages at Carver,33.713540,-84.390301

In [9]:
crime_2020 = crimerecord_202009_clean.append(crimerecord_202011_clean)
crime_2020

,offense_id,occur_date,occur_time,location,UC2_Literal,ibr_code,neighborhood,long,lat
0,200021209,1/2/2020,15:21,12 BROAD ST SW,HOMICIDE,NaN,Downtown,-84.391890,33.753520
1,200061707,1/6/2020,0:00,785 PEYTON AVE NW,HOMICIDE,NaN,Center Hill,-84.467700,33.776550
2,200100013,1/9/2020,23:45,1977 JONES AVE NW,HOMICIDE,NaN,West Highlands,-84.452080,33.787380
3,200151818,1/15/2020,17:15,549 JOSEPH LOWERY BLVD,HOMICIDE,NaN,West End,-84.417820,33.740010
4,200180440,1/18/2020,3:31,28 IRBY AVE NW,HOMICIDE,NaN,South Tuxedo Park,-84.380180,33.841020
...,...,...,...,...,...,...,...,...,...
7244,202740875,9/30/2020,12:27,238 PETERS ST SW,LARCENY-NON VEHICLE,23H,Castleberry Hill,-84.400728,33.747960
7245,202740912,9/30/2020,14:00,615 BOULEVARD SE,LARCENY-NON VEHICLE,23H,Grant Park,-84.368560,33.737731
7246,202660701,9/16/2020,7:00,1395 METROPOLITAN AVE SE,LARCENY-NON VEHICLE,23H,East Atlanta,-84.341593,33.742222
7247,202680663,9/19/2020,12:00,848 FOX ST NW,LARCENY-NON VEHICLE,23H,English Avenue,-84.415209,33.772028
7248,202741780,9/30/2020,16:48,17 BAKER ST NW,LARCENY-FROM VEHICLE,23F,Downtown,-84.388290,33.762930

In [10]:
crime_2020_2021=crime_2020.append(crimerecord_2021_clean)
crime_2020_2021

,offense_id,occur_date,occur_time,location,UC2_Literal,ibr_code,neighborhood,long,lat
0,200021209,1/2/2020,15:21,12 BROAD ST SW,HOMICIDE,NaN,Downtown,-84.391890,33.753520
1,200061707,1/6/2020,0:00,785 PEYTON AVE NW,HOMICIDE,NaN,Center Hill,-84.467700,33.776550
2,200100013,1/9/2020,23:45,1977 JONES AVE NW,HOMICIDE,NaN,West Highlands,-84.452080,33.787380
3,200151818,1/15/2020,17:15,549 JOSEPH LOWERY BLVD,HOMICIDE,NaN,West End,-84.417820,33.740010
4,200180440,1/18/2020,3:31,28 IRBY AVE NW,HOMICIDE,NaN,South Tuxedo Park,-84.380180,33.841020
...,...,...,...,...,...,...,...,...,...
9299,210280231,1/27/2021,21:15,2343 CAMPBELLTON RD SW,LARCENY-FROM VEHICLE,23F,Southwest,-84.465379,33.704558
9300,210280239,1/28/2021,02:37,485 LINDBERGH PL NE,AGG ASSAULT,13A,Lindbergh/Morosgo,-84.371098,33.820101
9301,210280257,1/28/2021,03:26,3186 US-78,LARCENY-FROM VEHICLE,23F,Collier Heights,-84.491515,33.785756
9302,210280267,1/28/2021,02:23,323 SPRING ST NW,LARCENY-FROM VEHICLE,23F,Downtown,-84.388717,33.763580
9303,210919771,1/20/2021,09:49,285 WILLIAMS ST NW,LARCENY-FROM VEHICLE,23F,Downtown,-84.390543,33.763189

In [11]:
crime_09_19=crimerecord_2009_2019_clean.rename(columns={'Report Number':"offense_id", "Occur Date":"occur_date", "Occur Time":"occur_time", 
                                                        'Location':'location',  'UCR Literal':'UC2_Literal','IBR Code':'ibr_code','Neighborhood':'neighborhood', 'Latitude':'lat','Longitude':'long'})

crime_09_19

,offense_id,occur_date,occur_time,location,UC2_Literal,ibr_code,neighborhood,lat,long
0,90010930,2009-01-01,1145,2841 GREENBRIAR PKWY,LARCENY-NON VEHICLE,2303,Greenbriar,33.68845,-84.49328
1,90011083,2009-01-01,1330,12 BROAD ST SW,LARCENY-NON VEHICLE,2303,Downtown,33.75320,-84.39201
2,90011208,2009-01-01,1500,3500 MARTIN L KING JR DR SW,LARCENY-NON VEHICLE,2303,Adamsville,33.75735,-84.50282
3,90011218,2009-01-01,1450,3393 PEACHTREE RD NE,LARCENY-NON VEHICLE,2303,Lenox,33.84676,-84.36212
4,90011289,2009-01-01,1600,2841 GREENBRIAR PKWY SW,LARCENY-NON VEHICLE,2303,Greenbriar,33.68677,-84.49773
...,...,...,...,...,...,...,...,...,...
342909,193652089,2019-12-31,2030,1385 SHARON ST NW,AGG ASSAULT,1315K,Hunter Hills,33.75486,-84.43287
342910,193650336,2019-12-31,432,262 PHARR RD NE,AGG ASSAULT,1314,Buckhead Village,33.83732,-84.37860
342911,193650603,2019-12-31,920,689 CASCADE AVE SW,AGG ASSAULT,1314,Westview,33.73636,-84.43680
342912,193651760,2019-12-31,1853,763 CASCADE AVE SW,AGG ASSAULT,1314,Westview,33.73483,-84.43750
342913,193652591,2019-12-31,2045,237 PEYTON PL SW,AGG ASSAULT,1314,Cascade Avenue/Road,33.72518,-84.45013

In [12]:
crime_09_21=crime_09_19.append(crime_2020_2021)
crime_09_21

,offense_id,occur_date,occur_time,location,UC2_Literal,ibr_code,neighborhood,lat,long
0,90010930,2009-01-01,1145,2841 GREENBRIAR PKWY,LARCENY-NON VEHICLE,2303,Greenbriar,33.688450,-84.493280
1,90011083,2009-01-01,1330,12 BROAD ST SW,LARCENY-NON VEHICLE,2303,Downtown,33.753200,-84.392010
2,90011208,2009-01-01,1500,3500 MARTIN L KING JR DR SW,LARCENY-NON VEHICLE,2303,Adamsville,33.757350,-84.502820
3,90011218,2009-01-01,1450,3393 PEACHTREE RD NE,LARCENY-NON VEHICLE,2303,Lenox,33.846760,-84.362120
4,90011289,2009-01-01,1600,2841 GREENBRIAR PKWY SW,LARCENY-NON VEHICLE,2303,Greenbriar,33.686770,-84.497730
...,...,...,...,...,...,...,...,...,...
9299,210280231,1/27/2021,21:15,2343 CAMPBELLTON RD SW,LARCENY-FROM VEHICLE,23F,Southwest,33.704558,-84.465379
9300,210280239,1/28/2021,02:37,485 LINDBERGH PL NE,AGG ASSAULT,13A,Lindbergh/Morosgo,33.820101,-84.371098
9301,210280257,1/28/2021,03:26,3186 US-78,LARCENY-FROM VEHICLE,23F,Collier Heights,33.785756,-84.491515
9302,210280267,1/28/2021,02:23,323 SPRING ST NW,LARCENY-FROM VEHICLE,23F,Downtown,33.763580,-84.388717
9303,210919771,1/20/2021,09:49,285 WILLIAMS ST NW,LARCENY-FROM VEHICLE,23F,Downtown,33.763189,-84.390543